spring:
  application:
    name: ai-super-agent
  #    激活本地文件
  profiles:
    active: local
  ai:
    dashscope:
      #        注意这里的导入格式
#      api-key: ${SPRING_AI_DASHSCOPE_API_KEY:your-api-key}
      api-key: sk-1579485902c84c5b83699923adb2a405
      options:
        model: qwen-plus
  #          开启日志调试
  logging:
    level:
      org.springframework.ai.chat.client.advisor: debug

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lx.aisuperagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: info
    com.lx.aisuperagent.advisor.MyLoggerAdvisor: info
