spring:
    # application.yml对需要调用大模型的配置
    ai:
      dashscope:
#        注意这里的导入格式
        api-key: sk-1579485902c84c5b83699923adb2a405
        chat:
          options:
            model: qwen-plus
# searchApi
search-api:
  api-key: c5083e75c47469db84f0f8bc64e955e53cf5b9763f18db0e7992006c6e23a57b

