spring:
    # application.yml对需要调用大模型的配置
    ai:
      dashscope:
#        注意这里的导入格式
        api-key: sk-1579485902c84c5b83699923adb2a405
        chat:
          options:
            model: qwen-plus
# searchApi
search-api:
  api-key: 87bbecc0dcc073d0328421cd3a5620298ffcd8af6809704eb7836050652e1fb8

