spring:
  application:
    name: ai-super-agent
    # application.yml对需要调用大模型的配置
    ai:
      dashscope:
#        替换你的key
        api-key: your-api-key
        chat:
          options:
            model: qwen-plus

