spring:
  application:
    name: ai-super-agent
  profiles:
    active: local
  ai:
    dashscope:
      #        注意这里的导入格式
      api-key: sk-1579485902c84c5b83699923adb2a405
      chat:
        options:
          model: qwen-plus
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi ????????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
#      ???????
      packages-to-scan: com.lx.aisuperagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn