spring:
  application:
    name: ai-super-agent
  # 激活本地配置文件
  profiles:
    active: local,sse  #需要时激活sse

  # AI 相关配置
  ai:
    dashscope:
      # 注意这里的导入格式
      api-key: ${SPRING_AI_DASHSCOPE_API_KEY:}
      options:
        model: qwen-plus
      embedding:
        options:
          model: text-embedding-v2
      vectorstore:
        pgvector:
          index-type: HNSW
          distance-type: COSINE_DISTANCE
          max-document-batch-size: 10000 # Optional: Maximum number of documents per batch


    #   mcp配置
    mcp:
      client:
        enabled: false
        request-timeout: 60s
        # sse链接方式
        sse:
          enabled: true
          port: 8127              # SSE 监听端口，可按需修改
          connections:
            qinglan_imageSearch_mcp:
              url: http://localhost:8127
  #        stdio:
  #          servers-configuration: classpath:mcp-servers.json





  datasource:
    url: jdbc:postgresql://rm-cn-rfd4pkzs1000112o.rwlb.rds.aliyuncs.com:5432/PG_Vector_ai
    username: my_pgsql
    password: PGsql123123
    driver-class-name: org.postgresql.Driver

#服务器配置
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lx.aisuperagent.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

#开启日志调试
logging:
  level:
    org.springframework.ai.chat.client.advisor: INFO
    org.springframework.jdbc: INFO
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG

# searchApi
search-api:
  api-key: ${SERPAPI_API_KEY:}

